---

- name: Playbook for delegate
  hosts: all
  become: yes
  
  vars:
    mytext: "Hello from Omsk"
   
  tasks:

  - name: Ping Test
    ping:
 
  - name: Unregister Server from Load Balancer
    shell: echo "This is server {{ inventory_hostname }} was deregistered from our Load Balancer, node name is {{ ansible_nodename }} " >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: Update my Databases
    shell: echo "UPDATING my DataBases...."
    run_once: true


  - name: Create file1
    copy:
      dest: /home/file1.txt
      content:
        This is file1
        on RUSSIAN "Privet iz Omska"
        on ENGLISH {{ mytext }}
    delegate_to: linuxUbuntu

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content:
        This is file2
        on RUSSIAN "Privet iz Omska"
        on ENGLISH {{ mytext }}

  - name: Reboot My Servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name:  Wait till My Servers will come up online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 5
      timeout: 40   
    delegate_to: 127.0.0.1
