
- name: Install Apache and Upload my Web Page
  hosts: Server_Ubuntu
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    dest_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt:
      name: apache2
      state: latest

  - name: Copy MyHomePage to Servers
    copy:
      src: "{{ source_file  }}"
      dest: "{{ dest_file  }}"
      mode: 0555
    notify: Restart Apache

  - name: Start Webserver and make enable on booy
    service:
      name: apache2
      state: started
      enabled: yes

  handlers:
  - name: Restart Apache
    service:
      name: apache
      state: restarted
